In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [5]:
df = pd.read_csv("Advertising.csv")
df




Unnamed: 0     TV  radio  newspaper  sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['TV','radio','newspaper']], df.sales)

LinearRegression()

In [7]:
reg.coef_  #my coefficients

array([ 0.04576465,  0.18853002, -0.00103749])

In [8]:
reg.intercept_  #intercept

2.9388893694594085

In [9]:
reg.predict([[200, 30, 60]])

C:\Users\exol1\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17.68546939])

In [10]:
0.04576465*200+0.18853002*30+ -0.00103749*60+2.9388893694594085 #sales 1

17.685470569459408

In [11]:
reg.predict([[230, 20, 55]])

C:\Users\exol1\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17.17829605])

In [12]:
reg.predict([[250, 20, 35]])

C:\Users\exol1\AppData\Roaming\Python\Python39\site-packages\sklearn\base.py:441: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([18.11433882])

In [13]:
0.04576465*230+0.18853002*20+ -0.00103749*55+2.9388893694594085 #sales 2


17.178297319459407

In [14]:
0.04576465*250+0.18853002*20+ -0.00103749*35+2.9388893694594085  #sales3

18.114340119459406